import unittest
import asyncio
from unittest.mock import patch, MagicMock, AsyncMock
from typing import Dict, Any

from news_app.editorial_pipeline import run_editorial_pipeline
from news_app.content_types import ContentType

class TestProductionPipeline(unittest.IsolatedAsyncioTestCase):
    
    def setUp(self):
        self.headline = {
            "title": "Breaking: Manchester United kalah 1-2 dari Arsenal",
            "source_url": "https://example.com/mu-arsenal",
            "source_name": "BolaSport",
            "summary": "Pertandingan seru di Old Trafford berakhir dengan kekalahan MU 1-2. Subscribe to our newsletter!",
            "published_at": "2024-01-01T12:00:00Z"
        }
        
    @patch('news_app.editorial_pipeline.story_exists', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.evaluate_semantic_duplicate', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.determine_content_type', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.extract_facts', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.detect_and_resolve_conflicts', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.gemini.generate_json', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.log_failure_audit', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.is_stale')
    async def test_successful_publish_flow(
        self, mock_is_stale, mock_log_audit, mock_gemini, mock_resolve_conflicts,
        mock_extract_facts, mock_determine_ct, mock_semantic_dedupe, mock_story_exists
    ):
        # Setup Mocks
        mock_story_exists.return_value = False
        mock_semantic_dedupe.return_value = ("NEW_STORY", None)
        mock_determine_ct.return_value = (ContentType.MATCH_REPORT, 0.95)
        mock_is_stale.return_value = False
        
        mock_extract_facts.return_value = {
            "core_facts": ["MU lost 1-2"],
            "content_type_specific": {"team_a": "Manchester United", "team_b": "Arsenal", "score": "1-2"}
        }
        
        # No conflicts
        mock_resolve_conflicts.return_value = (mock_extract_facts.return_value, False, {})
        
        # Mock Gemini Draft Generation
        mock_gemini.return_value = {
            "title": "Arsenal Permalukan Manchester United 2-1 di Old Trafford",
            "content": "<h2>Kekalahan Pahit MU</h2><p>Manchester United harus menelan kekalahan 1-2 dari Arsenal di depan pendukungnya sendiri.</p>"
        }
        
        # Execute
        result = await run_editorial_pipeline(self.headline, "bola")
        
        # Assertions
        self.assertIsNotNone(result)
        self.assertEqual(result["status"], "published") # Hardcoded in _finalize (wait, database save_news does this, pipeline returns draft)
        self.assertIn("content", result)
        self.assertIn("slug", result) # Generated by metadata formatter
        self.assertEqual(result["update_existing"], False)
        
        # Check source cleaner removed boilerplate
        # Original summary had "Subscribe to our newsletter!"
        self.assertNotIn("newsletter", self.headline["summary"].lower())
        
    @patch('news_app.editorial_pipeline.story_exists', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.evaluate_semantic_duplicate', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.log_failure_audit', new_callable=AsyncMock)
    async def test_semantic_dedupe_exact_skip(self, mock_audit, mock_semantic_dedupe, mock_story_exists):
        mock_story_exists.return_value = False
        mock_semantic_dedupe.return_value = ("EXACT_DUPLICATE_SKIP", "canonical_123")
        
        result = await run_editorial_pipeline(self.headline, "bola")
        
        self.assertIsNone(result)
        
    @patch('news_app.editorial_pipeline.story_exists', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.evaluate_semantic_duplicate', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.determine_content_type', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.extract_facts', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.detect_and_resolve_conflicts', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.gemini.generate_json', new_callable=AsyncMock)
    async def test_semantic_dedupe_material_update(
        self, mock_gemini, mock_resolve, mock_extract, mock_ct, mock_dedupe, mock_exists
    ):
        mock_exists.return_value = False
        mock_dedupe.return_value = ("MATERIAL_UPDATE", "canonical_123")
        mock_ct.return_value = (ContentType.MATCH_REPORT, 0.95)
        mock_extract.return_value = {"core_facts": ["Update"], "content_type_specific": {"team_a": "A", "team_b": "B", "score": "1-0"}}
        mock_resolve.return_value = (mock_extract.return_value, False, {})
        mock_gemini.return_value = {"title": "Update", "content": "<h2>Update</h2><p>1-0</p>"}
        
        result = await run_editorial_pipeline(self.headline, "bola")
        
        self.assertIsNotNone(result)
        self.assertEqual(result["canonical_story_key"], "canonical_123")
        self.assertTrue(result["update_existing"])
        
    @patch('news_app.editorial_pipeline.story_exists', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.evaluate_semantic_duplicate', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.determine_content_type', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.extract_facts', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.detect_and_resolve_conflicts', new_callable=AsyncMock)
    @patch('news_app.editorial_pipeline.log_failure_audit', new_callable=AsyncMock)
    async def test_unresolvable_conflict_blocks_publish(
        self, mock_audit, mock_resolve, mock_extract, mock_ct, mock_dedupe, mock_exists
    ):
        mock_exists.return_value = False
        mock_dedupe.return_value = ("NEW_STORY", None)
        mock_ct.return_value = (ContentType.HARD_NEWS, 0.9)
        mock_extract.return_value = {"core_facts": ["Fact"]}
        
        # Simulate unresolvable conflict
        mock_resolve.return_value = ({}, True, {"error": "Conflict between Tier 1 sources"})
        
        result = await run_editorial_pipeline(self.headline, "bola")
        
        self.assertIsNone(result)
        mock_audit.assert_called()
        self.assertEqual(mock_audit.call_args[0][3], "SOURCE_CONFLICT")

if __name__ == '__main__':
    unittest.main()
